/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConversationId = string;
export interface ConversationView {
  'id' : ConversationId,
  'participants' : [Principal, Principal],
  'messages' : Array<Message>,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Timestamp,
}
export type MessageId = bigint;
export type Timestamp = bigint;
export interface UserProfile { 'name' : string, 'avatar' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationsByMostRecentMessage' : ActorMethod<
    [],
    Array<ConversationView>
  >,
  'getMessages' : ActorMethod<[ConversationId, bigint, bigint], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[ConversationId, string], undefined>,
  'startConversationWith' : ActorMethod<[Principal], ConversationId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];