/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'avatar' : IDL.Opt(IDL.Text),
});
export const ConversationId = IDL.Text;
export const MessageId = IDL.Int;
export const Timestamp = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Timestamp,
});
export const ConversationView = IDL.Record({
  'id' : ConversationId,
  'participants' : IDL.Tuple(IDL.Principal, IDL.Principal),
  'messages' : IDL.Vec(Message),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationsByMostRecentMessage' : IDL.Func(
      [],
      [IDL.Vec(ConversationView)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [ConversationId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [], []),
  'startConversationWith' : IDL.Func([IDL.Principal], [ConversationId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'avatar' : IDL.Opt(IDL.Text),
  });
  const ConversationId = IDL.Text;
  const MessageId = IDL.Int;
  const Timestamp = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Timestamp,
  });
  const ConversationView = IDL.Record({
    'id' : ConversationId,
    'participants' : IDL.Tuple(IDL.Principal, IDL.Principal),
    'messages' : IDL.Vec(Message),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationsByMostRecentMessage' : IDL.Func(
        [],
        [IDL.Vec(ConversationView)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [ConversationId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [], []),
    'startConversationWith' : IDL.Func([IDL.Principal], [ConversationId], []),
  });
};

export const init = ({ IDL }) => { return []; };